export const TRACKS = [
  "3D & Motion Design",
  "Account Management",
  "Administration & Office Management",
  "Backend Development",
  "Brand Management",
  "Business Analysis",
  "Business Development",
  "Community Management",
  "Content Creation",
  "Content Strategy",
  "Copywriting",
  "Cybersecurity",
  "Data Analysis",
  "Data Science / Machine Learning",
  "DevOps & Cloud",
  "Digital Marketing",
  "E-commerce Management",
  "Email Marketing",
  "Executive Assistant",
  "Financial Analysis",
  "Frontend Development",
  "Full-Stack Development",
  "Graphic Design",
  "Growth Marketing",
  "Human Resources",
  "Illustration",
  "IT Support / Helpdesk",
  "Localization & Translation",
  "Machine Learning Engineering",
  "Mobile Development (iOS / Android / Flutter)",
  "Operations Management",
  "Photography",
  "Product Management",
  "Project Management",
  "Public Relations",
  "QA & Software Testing",
  "Recruitment / Talent Acquisition",
  "SEO Specialist",
  "Sales & Business Development",
  "Sales Development Representative (SDR)",
  "Site Reliability Engineering (SRE)",
  "Social Media Marketing",
  "Software Engineering",
  "Solutions Architecture",
  "Systems Administration",
  "Technical Writing",
  "UI/UX Design",
  "Video Editing & Motion Graphics",
] as const;

export type Track = (typeof TRACKS)[number];

export const EXPERIENCE_LEVELS = [
  "Fresh graduate / No experience",
  "Less than 1 year",
  "1 – 2 years",
  "3 – 5 years",
  "5+ years",
] as const;
